name: Log Time Job

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes

permissions:
  contents: write  # ✅ Ensures push permission for GitHub Actions

jobs:
  log_time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run logging script
        run: |
          chmod +x log_time.sh
          ./log_time.sh

      - name: Count logs
        run: |
          chmod +x count_logs.sh
          ./count_logs.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add log.txt log_count.txt
          git commit -m "Update log and log count" || echo "No changes to commit"
          git push
